server:
  port: 8080
  servlet:
    context-path: /backend
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://dnopusqwyexnzv:a7200afe29c850be352194fc81c4b602c1db8b9c0c338c0a190829db06e6621c@ec2-54-167-152-185.compute-1.amazonaws.com:5432/d623hl6pnkjabp
    username: dnopusqwyexnzv
    password: a7200afe29c850be352194fc81c4b602c1db8b9c0c338c0a190829db06e6621c
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto FullStack Santander - DIO